version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./app:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "4001"]

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: printo
      POSTGRES_PASSWORD: printo
      POSTGRES_DB: printo
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
